### ISSUE TITLE
Why mini-pix 4.2.0 and above firmware doesn't have this option VISO_TYPE = 1 to enable visual odometry

### ISSUE THREAD

**Issue by YJC-666** [ArduPilot/ardupilot_ros#26]
Why mini-pix 4.2.0 and above firmware doesn't have this option VISO_TYPE = 1 to enable visual odometry

**Comment by True2456** [comment]
https://custom.ardupilot.org/add_build most likely the build doesnt have visual odometry enabled. You can create a custom build with this link and enable visual odometry under AHRS
