### ISSUE TITLE
Way Point Following using Cartographer

### ISSUE THREAD

**Issue by KStickney** [ArduPilot/ardupilot_ros#27]
Hello,

I have ArduCopter, ROS2, and Gazebo all working. I can pull up the cartographer demo, and it works just fine as I fly around. How do I make it plan a path using RViz's 2d goal pose? Or even better yet, how do you make it generate way points on the map you made?

Thank you!

**Comment by srmainwaring** [comment]
@KStickney - nav2 support is included in this PR: https://github.com/ArduPilot/ardupilot_ros/pull/11. Note there are some issues upstream with nav2 support in Humble. The comments in the PR discuss the issues and possible solutions. See also: https://github.com/ArduPilot/ardupilot_ros/issues/25
